DROP TABLE IF EXISTS BUMON_TBL;
--DROP TABLE IF EXISTS TEAM19_MUSIC_TBL;

CREATE TABLE BUMON_TBL(
	BUMON_CD CHAR(3),
	BUMON_NM VARCHAR2(20),
	PRIMARY KEY(BUMON_CD)
	);
	
-- 気分テーブル
CREATE TABLE TEAM19_KIBUN_TBL (
    MOOD_CD VARCHAR2(5) NOT NULL ,
    MOOD_NM VARCHAR2(10) NOT NULL,
    PRIMARY KEY (MOOD_CD)
);
-- ジャンルテーブル
CREATE TABLE TEAM19_JANRU_TBL (
    JANRU_CD VARCHAR2(5) NOT NULL ,
    JANRU_NM VARCHAR2(10) NOT NULL,
    PRIMARY KEY (JANRU_CD)
) ;
-- 曲テーブル
CREATE TABLE TEAM19_MUSIC_TBL(
	MUSIC_CD NUMBER(5) AUTO_INCREMENT NOT NULL,
	MUSIC_NM VARCHAR2(30) NOT NULL,
	ARTIST VARCHAR2(30) NOT NULL,
	JANRU_CD VARCHAR2(5) NOT NULL,
	MUSIC_URL VARCHAR2(100) UNIQUE NOT NULL,
	MOOD_CD VARCHAR2(5) NOT NULL,
	LIKE_CNT NUMBER(5) DEFAULT 0 ,
	PRIMARY KEY(MUSIC_CD),
	FOREIGN KEY (JANRU_CD) REFERENCES TEAM19_JANRU_TBL(JANRU_CD),
    FOREIGN KEY (MOOD_CD) REFERENCES TEAM19_KIBUN_TBL(MOOD_CD)
);
ALTER TABLE team19_music_tbl ALTER COLUMN music_cd RESTART WITH 49;



-- コメントテーブル
CREATE TABLE TEAM19_COMMENT_TBL (
    COMMENT_CD NUMBER(5) NOT NULL AUTO_INCREMENT ,
    COMMENT_DATE DATE NOT NULL ,
    MUSIC_CD NUMBER(5) NOT NULL ,
    COMMENT_TEXT VARCHAR2(400) NOT NULL ,
    PRIMARY KEY (COMMENT_CD),
    FOREIGN KEY (MUSIC_CD) REFERENCES TEAM19_MUSIC_TBL(MUSIC_CD)
) ;
